In [14]:
import numpy

def cal_pop_fitness(equation_inputs, pop):
    fitness = numpy.sum(pop*equation_inputs, axis=1)
    return fitness

def select_mating_pool(pop, fitness, num_parents):
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        parent1_idx = k%parents.shape[0]
        parent2_idx = (k+1)%parents.shape[0]
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

def mutation(offspring_crossover):
    for idx in range(offspring_crossover.shape[0]):
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

In [15]:
equation_inputs = [4,-2,3.5,5,-11,-4.7]
num_weights = 6

sol_per_pop = 8
num_parents_mating = 4

pop_size = (sol_per_pop,num_weights)

new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

[[-3.27680211 -3.61498895 -1.67775739  3.07305045  1.84269956 -2.55850356]
 [ 0.94371391 -3.4004872   3.52600131  2.01131915  1.58138591  0.02520977]
 [-1.81274795 -0.37748194  3.39386127 -3.89596397 -2.27007729  1.96550917]
 [-2.75731714 -2.77939654 -1.03812545  2.74800056  2.75492446  3.95194057]
 [-0.37362892  0.00505114 -3.13680222 -3.57245516 -0.87377118  0.16277582]
 [-0.40234857 -0.44141638  3.74235532 -0.10803903  0.77800297 -3.79858045]
 [ 1.73609806 -1.35645532 -3.07477208  3.75598665 -0.99667825 -1.93530495]
 [ 1.4691088  -0.11914008 -2.00090876  1.72968394 -1.91170481  1.93142003]]


In [16]:
num_generations = 5
for generation in range(num_generations):
    print("Generation : ", generation)
    fitness = cal_pop_fitness(equation_inputs, new_population)

    parents = select_mating_pool(new_population, fitness, 
                                      num_parents_mating)
    
    offspring_crossover = crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    offspring_mutation = mutation(offspring_crossover)

    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

Generation :  0
Best result :  58.06914899964569
Generation :  1
Best result :  69.5795747848225
Generation :  2
Best result :  69.5795747848225
Generation :  3
Best result :  69.85680174025943
Generation :  4
Best result :  75.99682850500616


In [13]:
fitness = cal_pop_fitness(equation_inputs, new_population)
best_match_idx = numpy.where(fitness == numpy.max(fitness))
print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

Best solution :  [[[ 0.81473135 -3.38740212  3.62437429  3.9181553  -5.18457246
   -0.31420596]]]
Best solution fitness :  [100.81688124]
